steps:
  - name: 'python:3.9'
    id: 'Install dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt

  - name: 'python:3.9'
    id: 'Run main script'
    entrypoint: 'python'
    args: ['main.py']

options:
  logging: CLOUD_LOGGING_ONLY
